### ISSUE TITLE
.repeat / .endrepeat

### ISSUE THREAD

**Issue by ricardoquesada** [maxbane/vim-syntax-asm_ca65#1]
Thanks for creating the project!

Could you please add support for `.repeat` and  `.endrepeat` ?
I can send you a PR if you want, just let me know if I should use `asm_ca65PseudoFun` or something else. thanks.

**Comment by maxbane** [comment]
Oh yeah, not sure why I missed that. Totally send a PR -- I would actually suggest `asm_ca65Cond`, since `.repeat`/`.endrepeat` is more of a block structure than a pseudo function.

In fact, you could also try adding indent/dedent rules for `.repeat`/`.endrepeat` in `indent/asm_ca65.vim`, I think just by adding it to the regexps for the existing rules for `.if`, etc.

**Comment by ricardoquesada** [comment]
ok. pull request sent:
https://github.com/maxbane/vim-asm_ca65/pull/2

**Comment by maxbane** [comment]
Fixed by PR #2. Thanks!
